### ISSUE TITLE
DOAS fit not displaying properly in ReEvaluation dialog

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/NOVACProgram#104] opened 2019-07-24 22:01 UTC
In trying to ReEvaluate data from Ubinas, I found that the fit display is not working properly. A snapshot of the display is attached. The problem is in the 'Reference Fit' plot. Here, the fit residual is being displayed in red, but the SO2 cross section scaled with the fit coefficient is not being displayed, or rather it appears to be zero throughout the fit range when in fact it should be clearly visible on the scale of the plot. 

I am attaching the scan and fit settings files used for this analysis.

![2019-07-24_14-19-42](https://user-images.githubusercontent.com/15023271/61829752-6946a480-ae1e-11e9-9bbc-e7c3a170126b.png)

[NOVAC_FitExample.zip](https://github.com/NOVACProject/NOVACProgram/files/3428904/NOVAC_FitExample.zip)

**Comment by dnorgaard-usgs** [comment] 2019-07-24 23:50
Confirmed it works in 3.0 and it looks like this:

![image](https://user-images.githubusercontent.com/25251719/61835897-a61c9680-ae32-11e9-8646-da85d30a3a7f.png)

This bug was introduced in 3.1.

**Comment by mattias42** [comment] 2019-08-10 09:42
Bug fixed in commit 488f6d6 
The vector of data displayed in the graph and the vector of data returned from the evaluation have different conventions on how the data is stored. The evaluator stores the values in the evaluated region (a vector of fitHigh - fitLow values) whereas the view stores all the data (~2048 pixel values) which are zero outside of the fit-region (this seems to be necessary to get the x-axis correct on the display...).
Added an offset by fitLow in the extraction of the data to resolve this.

**Closed by mattias42** 2019-08-10 09:42 UTC
Labels: bug
