### ISSUE TITLE
Missing columns in Evaluation Log

### ISSUE THREAD

**Issue by mattias42** [NOVACProject/NOVACProgram#52] opened 2019-02-05 08:34 UTC
Ozone and Ring columns are missing from the evaluation-log.
Should be there same as for SO2.

**Comment by dnorgaard-usgs** [comment] 2019-02-26 20:25
I was able to test this today and Ozone/Ring columns are getting written to the evaluation-log when new pak files are downloaded, and also for re-evaluation.  Did you make a fix while making other changes in Evaluation?

**Comment by dnorgaard-usgs** [comment] 2019-03-01 21:40
Seems the issue was in the flux files, but is  now fixed.

On Wed, Feb 27, 2019 at 3:16 PM Norgaard, Diana  wrote:
Hi,

It looks like that is now fixed somehow (Mattias?).  I am seeing the columns for O3 and RING in the .txt files created when pak files are downloaded.  I also confirmed the problem existed in v3.0 that we released last year.  I attached the output from last year's version and the current version (you can see compiled date up top). 

Diana

On Wed, Feb 27, 2019 at 12:19 AM Santiago Arellano wrote:
Hi!

 

I’ve checked several examples of flux-files (txt files from individual scans which together form an EvalutionLog file) in the server and found that they don’t have information of column density, shift and squeeze with their respective errors for ozone and Ring, or putting it the other way, they only have information of those variables for SO2.

 

I believe the reason is that the version of February 2009 of the NovacProgram simply doesn’t write those results, and this is the version that we recommended to use because it proved to be the most stable. I think most observatories still use that version today.

 

The reason why I recognized this issue was that I am much more familiarized nowadays with the NovacPPP, which writes down the fitting results for all species.

 

As an example, see attached files for Cotopaxi from January 2017. The closest configuration file used by the program shows that all molecules should be included in the fit, but the file created by the NovacProgram only includes SO2 results. The same data, evaluated with the NovacPPP (with the name ending in ‘flux’), includes results for all species.

 

For the EvalutionLog the best is to keep it as in the example sent by Diana, which includes all molecules results and also which cross sections were used for the fit.

 

Best regards,

Santiago.

**Closed by dnorgaard-usgs** 2019-03-01 21:40 UTC
Labels: bug
